### ISSUE TITLE
Can't install in BTP

### ISSUE THREAD

**Issue by CoVeles** [SAP-samples/hana-developer-cli-tool-example#117]
I am working in a trial account with a BAS. But have an error every time.
I tried to use --noproxy registry.npmjs.org but result is the same
![Screenshot 2023-12-11 at 10 43 42](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/20125229/14712c89-8fb0-4f14-8943-64c698952373)
![Screenshot 2023-12-11 at 12 40 57](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/20125229/931cfaeb-66dc-483e-9669-263e6957c2d1)

**Comment by jung-thomas** [comment]
The problem seems to be specific to Business Application Studio.  The tool installs fine locally on Linux and Windows.  There is a module I'm using - [node-xlsx](https://www.npmjs.com/package/node-xlsx) which loads its dependency not via NPM but directly from a CDN: https://github.com/mgcrea/node-xlsx/blob/master/package.json#L24

This seems to not work currently from SAP Business Application Studio. It's either intentionally blocking non NPM installs or just some temporary misconfiguration. I couldn't say.  I know the installation worked last Thursday on BAS.  I did one myself.

But as a temporary work around I've created a new version of hana-cli that removes the usage of node-xlsx. I've had to disable the feature where you can export query results to Excel. Instead, you get this message:
![image](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/12159356/51e44331-dd30-493c-9902-934b0694eb91)

You can continue to export results to CSV as that uses a different approach. 

This will fix the installation issues with hana-cli until I can either find an alternative module or the issues with BAS are resolved. I'll push version 3.202312.1 in a few minutes which will contain this workaround.

**Comment by jung-thomas** [comment]
Confirmed. The newest version installs correctly in Business Application Studio now. 
![image](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/12159356/445d0eba-fdce-4106-a1c5-75e1dacd35c9)

![image](https://github.com/SAP-samples/hana-developer-cli-tool-example/assets/12159356/39707e54-ad60-44f7-9a08-5d4d3473d398)

**Comment by CoVeles** [comment]
Works now. Thank you very much.

**Comment by cuongus05** [comment]
@jung-thomas I see this error when I install UI5 Spreadsheet Importer. Please, help me fix this error. Thanks and Best Regards
![ảnh](https://github.com/user-attachments/assets/8cb6b1ba-119f-4f3c-a39e-d26d25ef8c2a)
user: zrap_demo_test3 $ npm install ui5-cc-spreadsheetimporter
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz failed, reason: Client network socket disconnected before secure TLS connection was established
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2024-12-12T10_10_12_528Z-debug-0.log
user: zrap_demo_test3 $

**Comment by jung-thomas** [comment]
@cuongus05 - I don't understand the connect between your comment and the hana-cli tool. You seem to be talking about a completely different package (ui5-cc-spreadsheeetimporter). I have no involvement in this package you mention. 6y7
