### ISSUE TITLE
Which port do I need to use for connect?

### ISSUE THREAD

**Issue by ThePlenkov** [SAP-samples/hana-developer-cli-tool-example#23]
Hi! Could you please advice which port do i need to use to connect via CLI?

Somehow it doesn't allow me to use 30015 ( we have instance 00 ) and it connects to 30041, but no commands work actually. 

Can it be connected that it's not a system database by a tenant?

Thank you!

**Comment by jung-thomas** [comment]
3XX15 and 3XX13 are standard for first tenant and systemDB.  XX being your instance number.  But a system can be configured by an admin to run on other ports, so there is no definite way to say without knowing how your system is setup.  Ask an admin or if you already have access to the system via another tool you can probably find out that way.  Even if you aren't sure how the system is connect if you can get into it and run this query:

```SQL
SELECT DATABASE_NAME, 
	SERVICE_NAME, 
	PORT, 
	SQL_PORT
FROM SYS_DATABASES.M_SERVICES
```

**Comment by ThePlenkov** [comment]
@jung-thomas  thanks for reply. Actually I have figured out. The port is 41 is correct one, but commands didn't work (like inspect) because there was no file default-env.json  but it was another one default-env-admin.json from connect -s call. This part confused me a little bit - i though i connected wrongly.

**Comment by jung-thomas** [comment]
Yes the designed flow is that you login with a HDI admin user or some other power user. These credentials are written to default-env-admin.json.  Those credentials are used automatically for some commands like the ones that create HDI containers.  Once a container is created it's credentials are written to default-env.json and used by the majority of commands.  This way the two sets of credentials can live side by side.  However there is the -a  option on most commands that will use default-env-admin.json instead of default-env.json.  Or if you want the login user to just be the default and not follow the HDI flow then just rename default-env-admin.json to default-env.json.
