### ISSUE TITLE
Issue with connecting to XS Advance Database

### ISSUE THREAD

**Issue by satharva** [SAP-samples/hana-developer-cli-tool-example#53]
Hi Thomas,
As suggested by you on the youtube video to move the conversation here, I have attached a screenshot of the error I am getting while connecting to the XS Advance Database using the hana-cli command. I tried to use the admin credentials for connecting but it still shows the same issue. 
![hana-cli issue](https://user-images.githubusercontent.com/77973707/122560570-5ff00200-d05e-11eb-86ef-c205d70d40a0.jpg)

But if I try to make a default-env.json using credentials I take from the application by going into the cockpit and getting the specific credentials I am able to do it but that gives me a access to a specific HDI Container, whereas what I want to do is make a new application and deploy it to XSA Databse like we do it in cloud by using the 'cf' command.

Regards
Atharva

**Comment by jung-thomas** [comment]
Odd that there is no connect error details.  One thing I did notice is that you said encrypt the connection, but then didn't supply any trust information.  This would make connection impossible and might be the source of the problem.  If you are using on premise HANA (especially HANA Express) you probably don't want to encrypt the connection.  Try false at this input. 

If that doesn't work they rung the hana-cli connect command with the --debug switch. That will trace a lot of inner details and will hopefully show what is going wrong.

**Comment by satharva** [comment]
I tried input 'false'  but I am not able to overwrite that 'true' command. The 'true' thing is coming on its own I have not made any changes.
I tried it with the --debug  command but I couldn't find any error from that. Here are the screenshots of the output I got
![cli issue 1](https://user-images.githubusercontent.com/77973707/122574883-c3356080-d06d-11eb-8cb6-535a7fc4c4ce.jpg)
![cli issue 2](https://user-images.githubusercontent.com/77973707/122574897-c6c8e780-d06d-11eb-8eef-f0b719425f13.jpg)

**Comment by jung-thomas** [comment]
>I tried input 'false' but I am not able to overwrite that 'true' command. The 'true' thing is coming on its own I have not made any changes.

Actually you are overriding the true in the above screenshot.  That (true) at the end of the prompt is tell you the default value.  When you supply f or false it is overriding the value. I can see it in the debug output.

But that wasn't the issue.  There was a bug in the handling of the connection details of the connect command itself. I did some refactoring in the last release and added some logic to look for connection files in parent and fallback directories. I guess this worked too well because my test case didn't fail when it should have. ;)  But you caught this situation in your environment because you'd never used hana-cli before.  Thank you! 

The debug trace you provided led me right to the issue and I've corrected now. Just published a new version to npm.  If you update to 2.202106.1 it should work fine now. Sorry for the trouble. Feel free to reopen issue if this doesn't solve it for you or if you have any additional questions.

**Comment by satharva** [comment]
Thank you for making changes, I am able to connect to the database now.

Now I am not able to create a HDI Container using my Admin user. While debugging I found the following error:
![cli_issue_1](https://user-images.githubusercontent.com/77973707/122729781-26eea200-d297-11eb-9f04-8aa15709ee1e.jpg)
![cli_issue_2](https://user-images.githubusercontent.com/77973707/122729791-2a822900-d297-11eb-9a64-8fe2adba48d8.jpg)
![cli_issue_3](https://user-images.githubusercontent.com/77973707/122729795-2b1abf80-d297-11eb-848c-51e4cabba85c.jpg)
