### ISSUE TITLE
Dependency to deprecated node pregyp in node modules of hana-cli with issues

### ISSUE THREAD

**Issue by RufatGadirov** [SAP-samples/hana-developer-cli-tool-example#58]
Hi there,

I am not able to build my mtar for my SAP CAP based application because of node-pre-gyp that is part of the hana-cli node modules. There are some dependencies with the deprecated node pregyp (latest is: @mapbox/node-pre-gyp": "^1.0.5").
I had to delete the hana-cli module and refresh my node modules in order to be able to successfully build an mtar file...because then the dependency to node pregyp was gone...

I already used these commands:
npm uninstall node-pre-gyp --save
npm install @mapbox/node-pre-gyp --save

In my package.json I have added the dependency: "@mapbox/node-pre-gyp": "^1.0.5",

...no effect...
I am getting this error:
ERROR could not package the "app-39818-srv" module when archiving: could not read the "/home/user/projects/app-39818-arbeitskleidung/gen/srv/node_modules/hana-cli/node_modules/.bin/detect-libc" symbolic link: stat /home/user/projects/app-39818-arbeitskleidung/gen/srv/node_modules/hana-cli/node_modules/detect-libc/bin/detect-libc.js: no such file or directory
make: *** [Makefile_20210714125238.mta:37: app-39818-srv] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20210714125238.mta p=cf mtar= strict=true mode=" command: exit status 2

Please check this issue from your side as well.

Thank you and BR
Rufat

**Comment by jung-thomas** [comment]
First - I'm not sure why you are adding hana-cli to the dependencies of your CAP project.  Generally you would just install hana-cli as a global package (`npm install -g hana-cli`). It really isn't necessary to install the tool within each project.  And you definitely don't want to add it to your dependencies and install it in production along with your application. It would serve no purpose within your CAP application and would only balloon the node_modules folder unnecessarily.

As to the dependencies you mention - @mapbox/node-pre-gyp or node-pre-gyp - that isn't even a direct dependency of hana-cli. It must be coming from one of the inner modules - maybe the @sap/hana-client since it has platform dependent modules. But that error is talking about detect-libc which node-pre-gyp requires at ^1.0.2 - resolving to 1.0.3. But why that dependency isn't there - I have no idea. 

But in the end I'm not sure how to recreate this error or even if it matters.  As said earlier I don't see any reason to include this module in your MTAR (or the package.json dependencies in general).  This module itself installs correctly on Windows, Mac and Linux; so I'm not sure what's different about what mbt is doing here. And even if it was some inner dependency (which I'm not sure it is), what's referenced is down in the stack of other modules not something I directly control, reference or use. 

Finally are you building in BAS?  If so are you sure you aren't just running out of file system space?  The MBT build command takes a lot of space and its easy to hit the limit on the Dev Space File System during this command. That could cause the npm install within the MBT build step to fail and might explain why some dependencies are suddenly just missing.

**Comment by RufatGadirov** [comment]
Hi Thomas,

thank you for your detailed response! I was very busy last week, so I am responding now. So, yes, I am using BAS and yes it happened in the past that I ran out of file system space..actually I just installed hana-cli via "npm install -g hana-cli" as you already described...I am not putting any dependency manually in there...it just happened out of nowhere during the time I wrote to you...I will try again, after my development is safely deployed...right now,  I can use the link to hana db explorer and I am fine....but I really just installed hana-cli and nothing else...it just seemed to me that it contains outdated package for node pregyp which produces this issue...

BR
Rufat

**Comment by draschke** [comment]
checking the version leads to this error message: **Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\node_modules\latest-version\index.js**
```

PS C:\Users\diraschk> hana-cli version
hana-cli: 2.202107.3
@sap/audit-logging: 5.0.0
@sap/cds: 5.3.2
@sap/cds-compiler: 2.4.4
@sap/cds-foss: 2.3.1
@sap/cds-dk: 4.3.3
@sap/cds-sidecar-client: 1.1.21
@sap/eslint-plugin-cds: 2.0.4
@sap/hana-client: 2.9.23
@sap/hdbext: 7.3.0
@sap/e2e-trace: 3.0.0
@sap/textbundle: 4.0.0
@sap/xsenv: 3.1.1
@sap/xssec: 3.2.2
sap-hdbext-promisfied: 2.202107.1
hana-cli home: C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\bin
Node.js: v14.8.0
Change Log: https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/main/CHANGELOG.md
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\node_modules\latest-version\index.js
require() of ES modules is not supported.
require() of C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\node_modules\latest-version\index.js from C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\bin\version.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\diraschk\AppData\Roaming\nvm\v14.8.0\node_modules\hana-cli\node_modules\latest-version\package.json.

```

**Comment by draschke** [comment]
WSL installation worked fine for me. Get only the same error msg while running command hana-cli version
**Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:** 
--> don't know what this means for me. do I've to do anything?
```

diraschk@vmn-it-ful-05:/mnt/c/git/priv$ hana-cli version
hana-cli: 2.202107.3
@sap/audit-logging: 5.0.0
@sap/cds: 5.3.2
@sap/cds-compiler: 2.4.4
@sap/cds-foss: 2.3.1
@sap/cds-dk: 4.3.3
@sap/cds-sidecar-client: 1.1.21
@sap/eslint-plugin-cds: 2.0.4
@sap/hana-client: 2.9.23
@sap/hdbext: 7.3.0
@sap/e2e-trace: 3.0.0
@sap/textbundle: 4.0.0
@sap/xsenv: 3.1.1
@sap/xssec: 3.2.2
sap-hdbext-promisfied: 2.202107.1
hana-cli home: /mnt/c/Users/diraschk/AppData/Roaming/nvm/v14.8.0/node_modules/hana-cli/bin
Node.js: v14.17.3
Change Log: https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/main/CHANGELOG.md
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mnt/c/Users/diraschk/AppData/Roaming/nvm/v14.8.0/node_modules/hana-cli/node_modules/latest-version/index.js
require() of ES modules is not supported.
require() of /mnt/c/Users/diraschk/AppData/Roaming/nvm/v14.8.0/node_modules/hana-cli/node_modules/latest-version/index.js from /mnt/c/Users/diraschk/AppData/Roaming/nvm/v14.8.0/node_modules/hana-cli/bin/version.js is an ES module 
file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from 
/mnt/c/Users/diraschk/AppData/Roaming/nvm/v14.8.0/node_modules/hana-cli/node_modules/latest-version/package.json.  

```

**Comment by jung-thomas** [comment]
The version command error is my fault. I updated a node module I was using within that command it had an incompatible change.  I've fixed that and will push to npm later today.  

As far as the other errors, they are coming from the sqlite3 module which in turn is coming in from @sap/cds-dk.  It's nothing that I'm using directly. Unfortunately sqlite3 has lots of open issues on these same.  The @mapbox/node-pre-gyp for example: https://github.com/mapbox/node-sqlite3/issues/1479 and the other build issue: https://github.com/mapbox/node-sqlite3/issues/1472

But these errors would seem be safe to ignore. No functionality in hana-cli actually uses Sqlite.  I tested an npm install, got these same errors but the tool still installed and worked fine. 
![image](https://user-images.githubusercontent.com/12159356/127145962-f7c1c001-1bfc-42b2-897b-a1b437592754.png)

Perhaps because I'm doing a npm dedupe to reduce the size of hana-cli overall there is some mixed dependencies when installing Sqlite within another tool.  But again I'm only getting Sqlite here because I have to pull in @sap/cds-dk to get the compile.to.openAPI command (which is only in @sap/cds-dk not @sap/cds unfortunately). 

I'll experiment with the npm dedupe and npm shrinkwrap process later to day to see if there is anything I can do about this. But for now it doesn't seem like it is actually causing any problems in the tool itself.

**Comment by jung-thomas** [comment]
I have pushed the update to the version command and it should work fine now again.  I did a few changes to the npm install before I prepare the shrinkwrap. On my machine at least it removed the nasty sqlite3 messages:
![image](https://user-images.githubusercontent.com/12159356/127148657-628e596a-48f5-4578-bd70-b948d67982bb.png)

Would be interested to see if it improved things on your side as well.
