### ISSUE TITLE
cli unable to connect to HANA on node v12.18.1 on macOS - Error Abort trap: 6

### ISSUE THREAD

**Issue by 6of5** [SAP-samples/hana-developer-cli-tool-example#6]
Any commands which require a connect to HANA are failing (Error Abort trap: 6) with node v12.18.1 on macOS 10.15.5, Example: When try to connect to HANA System (here SystemDB on HXE on docker) with connect command:
```
hana-developer-cli-tool-example $ node bin/cli.js connect
Input: Connection String  <host>[:<port>]:  hxehost:39017
Input: User:  SYSTEM
Input: Password:  ***********

Input: Encrypt connections (required for HANA As A Service or HANA Cloud):  false
Input: Optional: HDB User Store Key - Overrides all other Connection Parameters:  
Input: SSL Trust Store:  
⠙ 
Abort trap: 6
```

Environment is: node v.12.18.1 (using nvm) on macOS 10.15.5. When I switch to v12.14.1 of node everything is working fine. I have not tested other node releases

Debugging leads that the error happens in line 23 in client-factory.js of hdbext (v6.2.2 with hana-client 2.4.196) when _**client.connect(cb)**_ is executed:

```
var hdb = require('@sap/hana-client');
........


function createConnection(options, callback) {
  options = normalizeOptions(options);

  var client = hdb.createClient(options);

........

  async.series([
    function (cb) {
// Line 23
      client.connect(cb);
    },

```
BR HP

**Comment by jung-thomas** [comment]
I don't have a Mac, but I just tried on exactly node 12.18.1 on both Windows and Linux and it worked just fine.  It does seem that even in your case you are getting a problem actually from the underlying hdbext/hana-client not necessarily with hana-cli itself.  I'm also using the exact same version of hdbext and hana-client as you. 
![image](https://user-images.githubusercontent.com/12159356/85298614-4f6c7200-b472-11ea-9b1d-348dbb19a805.png)
I assume your usage of port 39017 is intentional.  Did you manually create another tenant which you are using here. 

I've never really known hdbext/hana-client not to return pretty detailed errors.  This Abort trap 6 must be something rather low level then.  On the other hand abort trap 6 seems to be a very generic error that doesn't tell you much about the actual error condition. 

I'm afraid my ability to help you out here is going to be rather limited. I don't see any indication that this issue is actually with content from this project but instead coming from the underlying modules. The fact I can't reproduce the error isn't helping much either.  But let me try to ask around internally and see if there is some known issue with Mac and this particular version of the hana-client.

**Comment by 6of5** [comment]
The issue feels weird to me, too. But as I could reproduce it also after de/reinstallation of node v12.18.1 I thought this is perhaps useful for others. I'm setting up a new macbook, so this a quit untouched system and rare condition.

You definetly right that this is not a direct issue of hana-cli but of the the used packages, but it does affects this great tool. 

Port 39017 is the standard port of the SystemDB of the HANA Express on Docker. For what ever reason, SAP used a different port on docker for SystemDB in contrast to binary, vm types.

**Comment by 6of5** [comment]
The issue is still reproducable with latest version of nodeJS (v12.18.2) and latest version of hana-cli (v1.202006.1) with contains @sap/hana-client: v2.5.86 on my local macbook

**Comment by jung-thomas** [comment]
I'm not sure how to move forward here as we've been unable to reproduce this error using the exact same versions on the Mac and Windows machines here. Although I've updated hana-cli and pulled in the updated version of hana-client via direct dependency; many of the DB operations still pass through hdbext module instead (which has not yet been updated to use the SPS 05 version of the hana-client yet). Perhaps if you are willing I could send you some simple node.js tests that use the hana client module directly without hdbext so its easier to test between its versions.

**Comment by 6of5** [comment]
If it is working on your side with macOS 10.15.x and nodeJS v12.18.1, then it seems not a general issue.

if the error occurs unfortunately only with me, then I close this issue. Thx

**Comment by jung-thomas** [comment]
Actually not saying we have to close it. I'd like to do a bit more troubleshooting if you are game. But it comes back on you to do some testing for us since we can't recreate on our Macs here at SAP.  I did create a small test here: https://github.com/jung-thomas/simple-hana-client-test
You should be able to just clone and run npm install.  It tests four different ways - with @sap/hana-client, with @sap/hdbext, with hdb, and with sap-hdbext-promisfied.  There are some subtle differences here that might help us narrow down the problem. We can also more easily test specific versions.  For example you might play with different @sap/hana-client versions directly to see what happens. It will also be interesting to see if there is a difference between the hdb and @sap/hana-client variants since they are implemented quite differently. 

You can maintain your connection parameters directly in the default-env.json file in the root. I left my parameters in there on purpose to help guide you. Just change you host, port, password, etc.  And yes I left my password for simplicity - its a well known one that I use only for public workshops.

**Comment by 6of5** [comment]
I did some test runs with simple-hana-client-test, quite interesting results:

1) **First test "source as is"** (hdbext is called first => Abort trap: 6):

```
macbook04:simple-hana-client-test $ node -v
v12.18.2
macbook04:simple-hana-client-test $ npm start

> simple-hana-client-test@1.0.0 start /Users/xxxx/git/simple-hana-client-test
> node index

simple-hana-client-test: 1.0.0
@sap/hana-client: 2.5.86
@sap/hdbext: 6.2.2
@sap/e2e-trace: 2.1.0
@sap/xsenv: 3.0.0
hdb: 0.18.0
sap-hdbext-promisfied: 2.202006.1

Abort trap: 6
```

2) **Second test "without hdbext"** (comment out testHdbext(), -> other options work fine):

```
version()
// testHdbext()
testHanaClient()
testHdbextPromise()
testHdb()
```
result:
```
simple-hana-client-test: 1.0.0
@sap/hana-client: 2.5.86
@sap/hdbext: 6.2.2
@sap/e2e-trace: 2.1.0
@sap/xsenv: 3.0.0
hdb: 0.18.0
sap-hdbext-promisfied: 2.202006.1


Test @sap/hana-client
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test hdb
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test sap-hdbext-promisfied
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
```

3) **hdbext is executed last** (->all work)

source:
```
version()
testHanaClient()
testHdbextPromise()
testHdb()
testHdbext()
```

result:

```
simple-hana-client-test: 1.0.0
@sap/hana-client: 2.5.86
@sap/hdbext: 6.2.2
@sap/e2e-trace: 2.1.0
@sap/xsenv: 3.0.0
hdb: 0.18.0
sap-hdbext-promisfied: 2.202006.1


Test @sap/hana-client
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test sap-hdbext-promisfied
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test hdb
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test @sap/hdbext
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
```


Noteable:
- saw in the package-lock.json that hdbext 6.2.2 is depending on "old" hana-client 2.4.196
- if i switch back to node 12.14.1 (i use nvm) then all tests run successfully
- switching to hana-client 2.4.196 instead of 2.5.96 (change in package.json and do again npm install) all tests except  hdb do not work

**Comment by 6of5** [comment]
btw HANA Client software is not installed on this macbook yet, 
like from https://tools.hana.ondemand.com/#hanatools

**Comment by jung-thomas** [comment]
Thank you for the testing.  That is actually very helpful.  Its interesting that just adjusting the order of the test cases causes the problem to go away. So it would seem like some sort of async, initialization or race condition. That would also lend itself to why we've been unable to recreate the problem internally. There could well be other factor at play like overall CPU Utilization. By any chance did you put the order back and perform the test multiple times?  Does it always fail with the original order of the tests?  I'm also quite relieved because this proves to me at least that its nothing specific that I'm doing in the hana-cli that's causing the situation.  

I'm going to keep this issue open for now (although isn't actually with this project) so we can continue to communicate on it. I will share the results of your testing with the HANA Client development team to see what they can find.  If you do have additional results or findings feel free to share them here. I also hope that soon we will have an hdbext version that directly uses the SPS05 HANA client as well. Simply by the virtue that there was a lot of internal development in the SPS05 of the Node.js HANA client; it may well solve the issue.

**Comment by grahamrobbo** [comment]
FYI - I am seeing the same behaviour on my Mac. Node v12.14.1 works fine. Let me know if I can do anything to help diagnose this.

**Comment by 6of5** [comment]
@jung-thomas I did test it multiple times and the error was reproducible, e.g. when i turn back to order again.

For me it looks like as the origin is in the "binary" part of hana-client 2.4.196 in context of node v12.18.x under macOS.

It seems that I'm not the only one anymore having this issue, as today also Graham Robinson reported on this.

**Comment by jung-thomas** [comment]
Thanks for updating - both of you.  I've forwarded to the HANA client team.

**Comment by grahamrobbo** [comment]
BTW @6of5 thanks for creating this issue - I would have been stumbling around in the dark for ages if I hadn't found it.
🙇‍♂️

**Comment by jung-thomas** [comment]
Just heard from development that we should be a couple of days away from a fixed version of hdbext being released. So hopefully we are close now.

**Comment by I355102** [comment]
I am also facing the same issue but getting different error "Process exited with code null" on line 23 in client-factory.js of hdbext (v6.2.2 with hana-client 2.4.196).
I am on macOS 10.15.6 and am facing same issue with both node versions 12.14.1 and 12.18.1.

![image](https://user-images.githubusercontent.com/21966268/89988898-ce756e00-dc9d-11ea-843f-1b5d4f9ad16d.png)

**Comment by 6of5** [comment]
The issue is solved with the updated version of the package @sap/hdbext v7.0.0 and latest @sap/hana-client v2.5.105

`
simple-hana-client-test: 1.0.0
@sap/hana-client: 2.5.105
@sap/hdbext: 7.0.0
@sap/e2e-trace: 2.1.0
@sap/xsenv: 3.0.0
hdb: 0.18.0
sap-hdbext-promisfied: 2.202006.1


Test hdb
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test @sap/hana-client
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test sap-hdbext-promisfied
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘
Test @sap/hdbext
┌─────────┬──────────────┬────────────────┐
│ (index) │ SESSION_USER │ CURRENT_SCHEMA │
├─────────┼──────────────┼────────────────┤
│    0    │   'SYSTEM'   │    'SYSTEM'    │
└─────────┴──────────────┴────────────────┘`

**Comment by jung-thomas** [comment]
Sorry that it took so long to get the @sap/hdbext updates published. I've been waiting on them myself and check npm each day.  You must have been right on top of the update as I see it was just done a few hours ago.  I'll do a battery of tests with the HANA Cli and the new version of the hdbext module yet today and hopefully get a new version pushed out with the updated dependency yet today as well.

**Comment by jung-thomas** [comment]
New version of hana-cli with the updated version of hdbext is now published.

**Comment by I355102** [comment]
Thanks, it works now. I just changed the @sap/hdbext to v7.0.0 and it worked with @sap/hana-client v2.5.86 also.
