### ISSUE TITLE
command serviceKey throws TypeError: Cannot set property 'encrypt' of undefined

### ISSUE THREAD

**Issue by 6of5** [SAP-samples/hana-developer-cli-tool-example#66]
The error occurs with the current version 2.202201.7 of hana-cli using HDI Container on BTP Trial. Output

```
hana-cli serviceKey repapp-hdi-dev repapp-hdi-dev-key2
Service Key repapp-hdi-dev-key2 created
Getting key repapp-hdi-dev-key2 for service instance repapp-hdi-dev as ......
TypeError: Cannot set property 'encrypt' of undefined
```

with version 2.202112.1 it works fine. The commit 681e734 from 202201-06 seems responsible, also it is marked as fix. I'm using **cf version 7.2.0+be4a5ce2b.2020-12-10**. Is there any newer version of cf cli necessary?

**Comment by jung-thomas** [comment]
I put that fix in because all of sudden I was getting double credentials section in the output.  Something must have changed with the output from the cf command.  I'm running cf version  8.1.0+034d929d7.2022-01-03

What do you see when just issue the cf service-key command?  Does the output begin with "credentials"? It does when I issue it now.
![image](https://user-images.githubusercontent.com/12159356/148825856-39f7f534-1f2b-45bb-b29f-9fefdae9a064.png)

**Comment by jung-thomas** [comment]
Sure enough it seems to be the cf cli version that makes a difference here.  I install cf version 7 and tried the same command against the exact same service instance and it returns different results. It doesn't have the credentials layer to the JSON output.
![image](https://user-images.githubusercontent.com/12159356/148826732-930db976-b1c6-4a0c-bb40-142207c65b84.png)

That kind of bites.  Let me see if I can come up with something in the hana-cli that handles both situations.

**Comment by jung-thomas** [comment]
Ok I've pushed version 2.202201.8 to npm https://www.npmjs.com/package/hana-cli and it has a fix for this issue.  It should now handle the return structures from both cf cli v7 and v8.
