### ISSUE TITLE
hana-cli based Containers and XS based Containers

### ISSUE THREAD

**Issue by Chathia** [SAP-samples/hana-developer-cli-tool-example#8]
Hello, The containers are getting created fine using hana-cli. We are looking to use the container in the Database explorer of Web IDE for Data Preview/SQL console. However, this container is not listed in Web IDE, and not also in the XSA Service Instances. 

Do we have an option to make it interchangeably work between XSA based containers - web ide and hana-cli

Reason: We are trying to build cap project completely based on VS Code and hana-cli. However, we need to use Web IDE for additional developments like Graphical Calc.Views, DB Explorer (Data Preview) etc.

**Comment by jung-thomas** [comment]
I assume you are using createContainer here https://github.com/SAP-samples/hana-developer-cli-tool-example#createcontainer
This command is really for people who have systems where there is no XSA. It allows you to create a container directly using the SQL procedure APIs. But in doing so it doesn't use the XSA or CF service broker at all.  Which is a good thing if you don't have XSA on your system. ;)

But this does mean that tools like the Database Explorer and Web IDE won't "see" the container because they are designed to only look at the service broker for HDI instances.  Its a little bit unfortunate that they don't also look into the database and just query containers directly. But then again they wouldn't have the service binding to access them via the container technical users. 

So if you want to work in both environments what I suggest to do is create the HDI container via the service broker.  You can create it via Web IDE, the Cockpit or the command line with at xs/cf create-service.  From hana-cli there is a separate command: serviceKey https://github.com/SAP-samples/hana-developer-cli-tool-example#servicekey  

This command is for this scenario. It connects to either the XSA or CF service broker and retrieves the existing HDI container instance details and writes them into a local default-env.json file for you.  This way you can still have the service broker create and manage your HDI container instances but also get easy access to them from the hana-cli. I personally use this approach to do exactly what you describe - to go back and forth from VSCode and Web IDE or Business Application Studio.

**Comment by Chathia** [comment]
Thank you for the response @jung-thomas ! In order to be interoperable with these toolsets, it makes sense to have the web-ide based containers and use the same in VSCode.
